name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repository code
        uses: actions/checkout@v2.3.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: 🛠 Install dependencies
        uses: bahmutov/npm-install@v1

      - name: 🔥 Build
        run: yarn build

      - name: 🚀 Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
